<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>陈美贤内衣店</title>
    <link rel="stylesheet" href="style.css"> #了解创建表格后将其填写进去
    <link rel="stylesheet" href="style copy.css">
</head>
<body>
         #《header》这种包含网站的logo
         #《nav》放置网站导览或主选单
         #《main》包含网页的主要内容   
         #《section》将内容做分类

    <section>     
    <h1>陈美贤内衣店</h1>
    <ul>
    <li<a href="#填写网站">最新消息</a></li>
    <li<a href="#填写网站">产品介绍</a></li>    
    <li<a href="#填写网站">联系我们</a></li>       
    </ul>
    <h2>迫不及待想抢先上架！</h2>
    <main>
    <section>
    <blockquote cite="填写网站">"据说可以让女孩们,<br>实现真正的穿衣自由"</blockquote>
    <img src="images/image470.png" alt="无痕内衣yaoenglish">
    <h2>迫不及待想抢先上架！</h2>
    </section>
    </main>
    <p><a hreef="#填写网站">了解更多</a></p>
    </section>
    <ol>
        <li>无痕内衣要点一</li>
        <li>无痕内裤要点二</li>
        <li>无痕文胸要点三</li>
        <li>无痕睡衣要点四</li>
        <li>无痕泳衣要点五</li>
    </ol>
    #《/footer》标注网站的版权信息
</body>
</html>
